version: '2.0'
services:
  my-elasticsearch761:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: my-elasticsearch761
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.seed_hosts=my-elasticsearch761
      - discovery.type=single-node
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata761:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  my-kibana761:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: my-kibana761
    environment:
      - ELASTICSEARCH_HOSTS=http://my-elasticsearch761:9200
      - I18N_LOCALE=zh-CN
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - my-elasticsearch761

  my-logstash761:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: my-logstash761
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/mysql-connector-java-5.1.38.jar:/usr/share/logstash/mysql-connector-java-5.1.38-bin.jar
    ports:
      - 9600:9600
    networks:
      - esnet
    depends_on:
      - my-elasticsearch761
volumes:
  esdata761:
    driver: local
  snapshot_folder:
    driver: local
networks:
  esnet: